Updated raffo.ttl with groupings
nicoroulet/moog pull request #12
Opened 2021-09-03 01:01 UTC by Pastitas

Added lv2 groups to make it more compatible with zynthian.

2021-09-03 09:09 UTC, nicoroulet requested changes
Thanks!

2021-09-03 09:09 UTC, nicoroulet commented on raffo.ttl
> +
Please remove newline

2021-09-03 11:32 UTC, Pastitas commented on raffo.ttl
> +
fixed on  d07bbcf

2021-09-03 14:07 UTC, merged

2021-09-09 21:48 UTC, julianpalladino commented
Thanks for the contribution @Pastitas!

2021-09-10 20:18 UTC, Pastitas commented
You're welcome! Thanks for the great synth!